version: "3.8"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/minjcho/inception/srcs/requirements/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/minjcho/inception/srcs/requirements/mariadb
      o: bind            

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      inception:
  
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      inception:
  
  mariadb:
    build:
      context: ./requirements/mariadb/.
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      inception:

networks:
  inception:
    name: inception
